version: '3'

services:
  api-controle-gastos:
    image: 'dev/projeto-tcc-api-controle-de-gastos'
    build:
      context: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-compose
      - pgadmin-compose
      - redis-compose
    environment:
      - ACTIVE_PROFILE=prod
      - FORUM_DATABASE_URL=jdbc:postgresql://postgres-compose:5432/controle-de-gastos
      - FORUM_DATABASE_USERNAME=postgres
      - FORUM_DATABASE_PASSWORD=password
      - CACHE_TYPE=redis
      - REDIS_HOST=redis-compose
      - REDIS_PORT=6379
    networks:
      - postgres-compose-network

  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "15432:5432"
    volumes:
      - ./volume/:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgrescompose@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

  redis-compose:
    image: "redis"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/redis-data:/data
      - ./volumes/redis/redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge